# Generated by Django 5.2.12 on 2026-04-14 10:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=20)),
                ('grade', models.CharField(choices=[('LGG', 'Low-Grade Glioma'), ('HGG', 'High-Grade Glioma')], default='HGG', max_length=5)),
                ('regions', models.JSONField(blank=True, default=dict)),
                ('opacity', models.IntegerField(default=70)),
                ('current_step', models.IntegerField(default=0)),
                ('current_step_name', models.CharField(default='Preprocessing', max_length=50)),
                ('total_steps', models.IntegerField(default=4)),
                ('metrics', models.JSONField(blank=True, null=True)),
                ('segmentation_file', models.FileField(blank=True, null=True, upload_to='results/')),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='uploads/')),
                ('original_name', models.CharField(max_length=255)),
                ('modality', models.CharField(choices=[('t1', 'T1-weighted'), ('t1ce', 'T1-CE'), ('t2', 'T2-weighted'), ('flair', 'FLAIR'), ('stacked', 'Stacked Input'), ('et_mask', 'Enhancing Tumor Mask'), ('wt_mask', 'Whole Tumor Mask'), ('tc_mask', 'Tumor Core Mask')], default='t1', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='segmentation.segmentationjob')),
            ],
        ),
    ]
