# Generated by Django 5.2.12 on 2026-04-21 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentationjob',
            name='input_files_json',
            field=models.JSONField(blank=True, default=list, help_text='List of input file paths or storage keys'),
        ),
        migrations.AddField(
            model_name='segmentationjob',
            name='mask_url',
            field=models.URLField(blank=True, default='', help_text='URL to the combined segmentation mask', max_length=1024),
        ),
        migrations.AddField(
            model_name='segmentationjob',
            name='preview_url',
            field=models.URLField(blank=True, default='', help_text='URL to the preview image', max_length=1024),
        ),
        migrations.AddField(
            model_name='segmentationjob',
            name='stacked_url',
            field=models.URLField(blank=True, default='', help_text='URL to the stacked NIfTI volume', max_length=1024),
        ),
        migrations.AddField(
            model_name='segmentationjob',
            name='user_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='segmentationjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed'), ('error', 'Error')], default='pending', max_length=20),
        ),
    ]
